name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '20'

      - name: Install dependencies
        working-directory: ./workers/tiltify-cache
        run: npm install

      - name: Publish Pages to Production
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jingle-jam-tracker
          directory: website
          branch: main
          wranglerVersion: '3'

      - name: Publish Worker to Production
        run: npm run deploy:production
        working-directory: ./workers/tiltify-cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Publish KV to Production
        run: |
          npm run kv-causes:production
          npm run kv-summary:production
          npm run kv-trends-previous:production
        working-directory: ./workers/tiltify-cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}