name: Deploy to DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '20'

      - name: Install dependencies
        working-directory: ./workers/tiltify-cache
        run: npm install

      - name: Publish Worker to Development
        run: npm run deploy:development
        working-directory: ./workers/tiltify-cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Publish KV to Development
        run: |
          npm run kv-causes:development
          npm run kv-conversion-rate:development
          npm run kv-summary:development
          npm run kv-trends-previous:development
        working-directory: ./workers/tiltify-cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Publish Pages to Development
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: JingleJamTracker
          directory: /website
          wranglerVersion: '3'